kind: pipeline
name: go1.15
type: docker

steps:
  - name: test
    image: golang:1.15
    commands:
      - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov-token
      files:
        - coverage.txt

---
kind: pipeline
name: go1.14
type: docker

steps:
  - name: test
    image: golang:1.14
    environment:
      GO111MODULE: "on"
    commands:
      - go test ./...

---
kind: pipeline
name: go1.13
type: docker

steps:
  - name: test
    image: golang:1.13
    environment:
      GO111MODULE: "on"
    commands:
      - go test ./...

---
kind: pipeline
name: go1.12
type: docker

steps:
  - name: test
    image: golang:1.12
    environment:
      GO111MODULE: "on"
    commands:
      - go test ./...


---
kind: pipeline
name: go1.11
type: docker

steps:
  - name: test
    image: golang:1.11
    environment:
      GO111MODULE: "on"
    commands:
      - go test ./...

---
kind: pipeline
name: go1.10
type: docker

workspace:
  base: /go
  path: src/github.com/mennanov/fieldmask-utils

steps:
  - name: test
    image: golang:1.10
    commands:
      - go get -t ./...
      - go test ./...

---
kind: pipeline
name: go1.9
type: docker

workspace:
  base: /go
  path: src/github.com/mennanov/fieldmask-utils

steps:
  - name: test
    image: golang:1.9
    commands:
      - go get -t ./...
      - go test ./...

---
kind: pipeline
name: lint
type: docker

steps:
  - name: lint
    image: golang:1.15
    commands:
      - go get -u github.com/mgechev/revive
      - revive -formatter=friendly -config=revive.toml -exclude=vendor/... ./...
